festSponsors = [
    'acmchapter.jpg',
    'axure.png',
    'balsamiq.png',
    'bitonic.jpg',
    {
        'img': 'bugsee.png',
        'link': 'https://www.bugsee.com/'
    },
    'challengerocket.png',
    'chem.png',
    'cloudsploit.png',
    'creativetim.png',
    'cubelelo.jpeg',
    {
        'img': 'deepsource.png',
        'link': 'http://deepsource.io'
    },
    'developercircle.jpg',
    'devfolio.png',
    'dishtv.png',
    'edtimes.jpg',
    'gail.png',
    'gfg.png',
    'codechef.png',
    'gitkraken.png',
    'hellointern.jpg',
    'hostgator.png',
    'ieee.png',
    'intelligentchange.jpg',
    'interntheory.png',
    'invision.png',
    'jamboree.jpg',
    'jetbrains.png',
    'linode.png',
    'madeeasy.png',
    'matic.png',
    'moz.jpg',
    'nestle.png',
    'pokerbaazi.png',
    'proto.io.png',
    'quiknode.png',
    'shivnaresh.jpg',
    'sketch.PNG',
    'smaash.png',
    'stickermule.png',
    'stickeryou.png',
    'thecollegefever.png',
    'tilde.png',
    'wolframalpha.png',
    'womenwhocode.jpg',
    'XSINFOSOL.png',
    '_techdomains.jpg'
]