nontechJson = [{
        'id': 1,
        'name': '3D Modelling',
        'img': '/nontech/3dmodel3.png',
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "1 Member",
        'regLink': "https://bit.ly/2M5kB5y", 
        'description': "An event in which the participants will be tasked to create 3D Models using a set of software and in a given time. The 3D Model render must be complete in all aspects including lighting, material, texture, animations (if added to the model) etc. The participant will have the freedom to choose his/her choice of a software. She/he will be asked to create the “art” based on a specific theme. The participant will be rated based on the design, authenticity, execution style and relevance to the theme of the final render output.",
        'rules': ["Every participant can participate in any of the three segments. He/she can also participate in more than one segment. However, since all segments began at the same time, hence no extra time will be given. Hence, all such participants must plan accordingly.", "Usage of online material for ideas/ models/ techniques/ materials/textures is allowed. However, any such usage must be referenced in a sheet provided. If any participant is found using online materials without referencing, he/she will be penalized and may lead to disqualification.", "Refrain from using models or projects as it is. If found doing so, it will lead to disqualification.", "For final render outputs, a participant can get an extra 20 minutes. This is only applicable for the final render. If the render output is not provided after the allotted 20 minutes, no extra time will be given whatsoever."]
    }, {
        'id': 2,
        'name': 'Weaving Stories',
        'img': '/nontech/weavingstories.png',
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "TBA",
        'regLink': "https://bit.ly/2SecFA0",
        'description': "\"If you can see stories forming around you, give them flight!\"<br>This is an event that fuses the technical skills of designers and literary skills of writers to form stories that are visually appealing and will enthrall the audience. The event merges two fields which look different but at the same time share so much in common and have tremendous scope for collaboration in the future.<br>So step into the scene and let it drip from your fingertips.",
    	'rules':["1. The teams will not be allowed to prepare any kind of template beforehand.","2. The participants, however, must avoid plagiarism at all costs."]
    }, {
        'id': 3,
        'name': 'Beat Slayer VR',
        'img': '/nontech/beatslayervr.png',
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "1 Member",
        'regLink': "https://bit.ly/2O8AFq7", 
        'description': "A Virtual Reality game where everyone competes for supremacy. You dance to the beat and slay down obstacles to thrive. To compete and to come out as a victor is your one and only goal as you battle your diminishing stamina in a challenge against your rivals to set an ultimatum. Go on ahead and be a winner!",
        'rules': ["The rules are very simple, play as long as you don’t die.", "A player gets to play 2 chances, the higher score would be considered.", "All High Scores would be maintained by us and in case of any dispute, the final say will be ours.", "Anyone found tampering with the hardware or damaging it will have to pay a fine or bear the cost of equipment. All Participants will be made aware of this rule especially."]
    }, {
        'id': 4,
        'name': 'The Big Bang',
        'img': '/nontech/BigBang.png',
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "1-2 Members",
        'regLink': "http://bit.ly/big_bang_iiitd", 
        'description': "Esya’19 presents you Big Bang, a cosmic quizzing experience. A brainchild of Astronuts, the astronomy club at IIITD, we bring to you an event like none before, where we won't just test your objectivity but your vision and imagination.<br>Get ready for a special experience relative to none other. We aim to not only educate but also entertain. With topics ranging from the observable universe to light years away, we have it all in the bag. It won’t be just plain old questions and answers, but something you won’t even find in a galaxy far far away. It’s time we made quizzing fun again.",
        'rules': ["Team size of at most two is allowed", "Cross-college/cross-school teams are allowed", "Use of any electronic gadget(mobile phones, laptops, tablets, calculators, etc.) is prohibited."]
    }, {
        'id': 5,
        'name': 'BioWhiz',
        'img': '/nontech/BioWhiz.png',
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "1-2 Members",
        'regLink': "http://bit.ly/BioWhiz", 
        'description': "\"The Science of today is the technology of tomorrow.\"<br>We, at Esya’19, present to you BioWhiz, which is a unique biology quiz contest, in which anyone with even the slightest hang of Biology can participate. If Computational Biology and the latest Biological technologies fascinate you, then you’ll definitely have an edge. To add further excitement, we might also ask some questions based on sci-fi movies.",
        'rules': ["Multiple teams are allowed from a school/college.", "Electronic Gadgets are not allowed.", "If any question requires theoretical information, then we might provide the reading material."]
    }, {
        'id': 6,
        'name': 'Chess',
        'img': '/nontech/chess.png',
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "4 Members",
        'regLink': "https://docs.google.com/forms/d/1UyAcpjilsQqRGv0nYupmRSjHUY4MOaqOwQUt4F2KGRE/edit?usp=sharing",
        'description': "\"Trust your instincts. They are usually right.\"This is a semi-rapid open individual unrated chess tournament for rated as well as unrated players.<br><br>",
        'rules': ["System of play- The tournament is Swiss format based where every player will play all the rounds(that means no knockout) and the winner will be decided on the basis of total points and tie-breakers.", "The time control of this tournament will be 10+5 which means 10 minutes with 5-sec increment on every move for each player.", "Default Time (Walk Over Time)- The default time will be 15 minutes and if a player doesn’t reach his board within 15 minutes after the start of the round a forfeit will be considered.", "Tie Break- In case of a tie, the latest FIDE Rules shall come into effect. ", "The decision of the Arbiter/Event Coordinators shall be final in case of any discrepancies. Along with the rules mentioned above, all the rules outlined by FIDE for Tournament shall be applicable. Rules and eligibility criteria are subject to change in the spirit of the Fest and the final decision rests with the Arbiter and the organizing team."]
    }, {
        'id': 7,
        'name': 'Faking the Research',
        'img': '/nontech/FakingtheResearch.png',
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "2-4 Members",
        'regLink': "http://bit.ly/fakingtheresearch",
        'description': "Can you concort tales to support your hypothetical scenarios?<br>Can you find your way out of any situation without raising suspicion? <br>Do you take pride in your ability to spin unbelievable yarns?<br>If your answer to these questions is yes, then this is the event for you!<br>Convince the world of your fake theories and ideas.",
        'rules': ["We’ll have an online round where participants can send in their fake research. Top 10 teams will be shortlisted, who will get to present their work on the day of the event."]
    }, {
        'id': 8,
        'name': 'FOQS',
        'img': '/nontech/FOQS.png',
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "1-5 Members",
        'regLink': "http://bit.ly/FOQS_IIITD",
        'description': "\"Taking an image, freezing a moment, reveals how rich reality truly is.\"<br>Esya returns with its Photography competition FOQS. We invite all photography enthusiasts, who wish to share important stories and influence the way people think through their images.",
        'rules': ["No Photograph should have any watermark or copyright."]
    }, {
        'id': 9,
        'name': 'Fun Arena',
        'img': '/nontech/FunArena.jpg',
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "1",
        'regLink': "https://bit.ly/2GKDRC6",
        'description': "Where the fun never ends! Fun Arena organizes the following fun-filled events:<br>○ Air Hockey-A table game in which two players attempt to score points by using a handheld paddle to shoot a plastic disk across a surface with minimal friction into the opponent's goal. <br>○ Food Binge- Who eats the most in a given amount of time. Can be a Golgappa eating competition, or fries eating the competition. But don’t always expect tasty food! <br>○ Pong-Pong - A drinking game in which players throw a ping pong ball across a table with the intent of landing the ball in a cup of bitter juice on the other end so as to force them to drink it. The game typically consists of opposing teams of one or two players per side with 6-10 cups set up in a triangle formation on each side.<br>○ Laser tag - A tag game played with guns which fire infrared beams. Infrared-sensitive targets are commonly worn by each player and are sometimes integrated within the arena in which the game is played.",
        'rules': ["The participant should be registered beforehand (either online or on campus).", "The payment has to be made on the spot (Cash OR PayTM).", "The participant should not touch the table or the puck.", "The participant should avoid throwing the disc out of the table. If this happens three times in a game, the participant can be disqualified.", "The Participant should finish 1 food item before switching to the other one.", "The definition of “finishing a specific food item” would be predefined by us.", "The Participant will stand at a distance of at least 1m from the table.", "The Participant should not extend his hands beyond the table while shooting the ball.", "The participants would get fixed and limited ammo for the round."]
    }, {
        'id': 10,
        'name': 'Video Editing',
        'img': '/nontech/VideoEditing.png',
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "TBA",
        'regLink': "bit.ly/videoesya",
        'description': "This is a Video Editing/ Film making Competition. In this event, participants will be judged on the amalgamation of many skills like script writing, photography, video editing etc. A short film is expected to be made during this event pertaining to the theme provided in the competition.",
    	'rules': ["1. It can be a film. A documentary. Doesn’t matter.","2. The videos should clearly show your skills in videography, scripting and video editing.","3. It should entirely be relatable to the topic.","4. Should have captions. (Text to speech not preferred)","5. Use of the Internet is allowed.","6. Duration of unoriginal footage (Eg. From Youtube) shouldn’t exceed 60 seconds.","7. We will provide a 10-second video stating that this film was made during Esya 19’.","8. The video should be of 420-480 seconds (excluding the 10-second allotted video) ","   with a relaxation time of 10 seconds.","9. A bibliography must be provided in the end."]
    },  {
        'id': 11,
        'name': 'HuntIT',
        'img': '/nontech/HuntIT.png',
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "1-5 Members",
        'regLink': "https://bit.ly/2xMQKqt",
        'description': "Experience an enthralling escape from the monotonous routine to an exhilarating treasure hunt, packed with a cauldron of hypercompetitive scenarios, unforeseen challenges and mind bending clues giving you an adrenaline high - one of the best feelings in the world - pumping your veins so full of thrill that confidence will become an exuberant trait.<br>King Ragnar Lothbrok, the famous Viking is dead, killed by King Aella of England. His sons have assembled a large heathen army to exact vengeance from King Aella. Norse warriors from Denmark, Norway and Sweden coalesce to serve the cause. Knowing the route to England brings with it unexpected mysteries and jeopardous events, are you ready to venture? Set sail as fast as you can, survive the storms, navigate through the risk, and lead your heathen army to England before the waves wash you into the sea. Impress the Gods, earn your place in Valhalla and take home the treasure.",
        'rules': ["HuntIT is a completely non-tech fun event and will not give any unfair advantage to the ","participants from technical colleges or schools. It is an event to test your analytical skills.","1. The team size is 1-5. Cross-college and cross-school teams are allowed. Multiple teams ","   from the same college are allowed.","2. It will be a two-day event in which the rounds of the second day, which will be the ","   theme-based day, will require the teams to race across the city to carry out the hunt successfully.","3. Teams will face elimination through subsequent rounds leading up to the final day of the hunt","4. No participant can be a member of more than one team.","5. Changing teams after registration is prohibited. Participants are requested to bring ","   smartphones or at least mobile phones with internet so that they can carry out the hunt","   without being held back due to the lack of internet. Even though we might be able to ","   provide internet connection inside the campus, you’ll rely on your own internet packages ","   when you are off campus.","6. Discussing answers with other teams would be regarded as a violation of rules and an","   appropriate penalty would be applied (including instant elimination).","7. On day 2, only public transport will be allowed for travelling to places. Anyone found","   using their own vehicle will be eliminated.","8. In the elimination rounds, teams solving the rounds after a certain number of teams ","   would be eliminated.","9. Organizers have the right to disqualify any team if they break any rule.","10.In case of any discrepancy, the decision of the organisers will be final and binding."]
    }, {
        'id': 12,
        'name': 'IPL Auctions',
        'img': '/nontech/ipl.png',
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "2-4 Members",
        'regLink': "http://bit.ly/2JBWV7v",
        'description': "We invite all cricket fans to give an enthusiastic shot.<br>Experience the unparalleled escaping in the mock auction of IPL players, compete for them, wait for the perfect bid to finally make them yours.<br>Try your own combination of players and see if your desired team will stand out or fade in the shadow of others.<br>If cricket is a sport that ignites the fire within you, then do yourself a favour and come be a part of our event!",
    	'rules': [ 
            "1. Every team will have 100Cr in-game currency (tentative) as the purse amount.",
            "2. Teams can add a limited amount to the purse money using real currency limited number of times",
            "3. Both male and female players will be up for the auction.",
            "4. Every player will have a base price, bids have to increase by specific amounts (decided ",
            " based on base price + number of bids).",
            "5. Every player will have a specific rating based on his career stats.",
            "6. Every player will have a hidden maintenance cost, disclosed to the buyer after the bid.",
            "7. A team needs to meet the following requirements -",
            "	7.1 4 Bowlers",
            "	7.2 4 Batsmen",
            "	7.3 1 Wicketkeeper","	7.2 1 Allrounder","	7.5 1 Coach","8. For every player, the rating will increase by 4 for every other player of the same national ","   team and decrease by 3 otherwise.","9. Players will have classes like GOAT(Greatest of All Time), Legendary, Normal, etc.","10. Legendary players will have an extra skill like Sachin Tendulkar will boost points by +1","	for every other player.","11. Multiple rounds of the auction may be held based on unsold players and team requests.","12. Teams can sell players among themselves (limited).","13. Teams give up a player for auction again but for a 70 starting price."]
    }, {
        'id': 13,
        'name': 'Poker',
        'img': '/nontech/poker.png',
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "TBA",
        'regLink': "http://bit.ly/esyapoker",
        'description': "It's Poker!<br>Get ready to test your bluffing skills. Don't hesitate to go all-in on this poker tournament. Come and battle out against other players to become the poker king of the table.",
    	'rules':["The game begins with every player on a table (8 players) having chips worth Rs. 100. Initially,"," the small blind will be 10, and the big blind 20, which might increase later if the tournament gets","too long. Every player is given 2 cards, after which the dealer eventually opens up 5 cards on the","table (no. of table cards being in this sequence 0+3+1+1=5). Finally, a player makes the","combination of the best 5 cards out of the 7 cards he can choose from and the pot is distributed","accordingly. A player is knocked out when he is left with no chips. The first, second and third","positions will be decided on the basis of the last person being knocked out. If the players having","second or third position lose to the first position in the same chance and get knocked out","together, then the second position is awarded to the player who had more money."]
    }, {
        'id': 14,
        'name': 'PUBG',
        'img': '/nontech/pubg2.png',
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "TBA",
        'regLink': "http://bit.ly/2KdqkoM",        
        'description': "Get Ready for WINNER WINNER CHICKEN DINNER!<br>A two day event, with different tournaments on each day. <br>On each day, 3 matches will be held. Map will be Sanhok. Out of those matches, top 8 teams will be selected and these 8 teams will play the final round.",
    	'rules':["1. A team can participate in any number of times in the event.","2. The players can form on the spot teams on the day of the fest.","3. Wifi is provided, but it is up to the participant to use their own mobile data. Use of","emulator is strictly prohibited.","4. Any types of unfair means, will lead to strict disqualification from the event completely."]
    }, {
        'id': 15,
        'name': 'Pwned',
        'img': '/nontech/PWNED.jpg',
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "TBA",
        'regLink': "https://bit.ly/2Yj1GLY",      
        'description': "Don't forget to shoot some long range goals or boast your amazing nutmeg skills in FIFA19. Come and challenge skilled players for the ultimate legacy!",
    	'rules':["Settings: Standard settings","Match durance: 10 minutes (5 minutes per half)","Game speed: Normal","Level: Legendary","1.2 All matches should be played by a  ́Friendly Match ́.","1.3 Only tactical defense is allowed.","1.4 It's forbidden to use custom formations, only the standard formations are allowed to use. (So don't use the square button to change the position of players","1.5 All Clubs and International Teams can be used.","1.6 FIFA 19 will be played on PS4.","1.7 A total of 2 minutes per match will be provided to a player to set up his team settings,","substitution and formation.","1.8 Player cannot use his own custom player to play match.","1.9 A player may bring his own controller to play a match ."]
    }, {
        'id': 16,
        'name': 'Rebuttal',
        'img': '/nontech/Rebuttal.png',
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "TBA",
        'regLink': "https://bit.ly/2Ss5Db4",
        'description': "Rebuttal is the ultimate test of your wit and your grit. It will pit you against some of the best debaters in the country in multiple rounds of high quality debating. Are you ready to engage in such fierce competition?<br><br>"  
    }, {
        'id': 17,
        'name': 'Speed Cubing',
        'img': '/nontech/SpeedCubing.jpg',
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "TBA",
        'regLink': "http://bit.ly/SpeedcubingESYA19",
        'description': "\"Go Fast or Go Home!\"<br>Speedcubing is a Rubik's cube competition, for which many of the speedcubers wait. This event is for all those people who get excited when they see a Rubik’s cube or the ones who think they have some skills and can compete with other cubers.",
    	'rules':["1. Solving cube before starting stack mat will lead to a penalty.","2. Stopping stack mat before finishing cube will lead to a penalty.","3. Starting cube after completing inspection time will lead to a penalty. Make sure that you","start solving cube before the timer runs out of time.","4. There will be a time limit after the time limit is crossed, the attempt will be stopped and","will be considered DNF (Did not finish).","5. A puzzle is solved when all color parts are reassembled and all parts are aligned within","the limits specified below-"," a. If one face of the cube is misaligned by at most 45 degrees. Else it is considered","equivalent to requiring one more move to solve the cube and in such a case there","will be a penalty of 2 seconds.","b. In any other state in which more than one move is required to solve the cube, the","puzzle is considered unsolved (DNF).","6. The decision of the event head is final.","7. Event head can modify the rules according to the situation, assuring that no biasing","happens."]
    }, 
]